import { readFile, writeFile } from "node:fs/promises";
import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";
const schema = JSON.parse(
  await readFile("schemas/article.schema.json", "utf8"),
);
const ajv = new Ajv({
  allErrors: true,
  code: { source: true, esm: true },
  unicode: false,
});
const validate = ajv.compile(schema);
const code = standaloneCode(ajv, validate);
await writeFile(
  "src/core/article-validator.js",
  "// Generated by scripts/build-schema.mjs; safe under a CSP without unsafe-eval.\n" +
    code +
    "\n",
);
